@Echo Off
Rem This file is placed in the public domain.
Rem
Rem Wrapper file to invoke mkvimball.vim.js with
Rem CScript script host and no logo displayed.
Rem
Rem Generated by the mkvimball vim script
Rem (www.vim.org/scripts/script.php?script_id=4219).
Rem
Rem The .js script output is a command line that is
Rem placed in a batch file and Call'ed.

Rem input file contents marker: a7ec181d243150b7e40823f224174a281f46e986
Rem cmd script contents marker: c6c4b8449b050fd4a288662c85ab3043343541e3

Rem Invoke .js script and save output
CScript //NoLogo "%~dpn0.js" %* >"%TEMP%\mkvimball.cmd"
If ErrorLevel 1 (
    If Exist "%TEMP%\mkvimball.cmd" (
	Type "%TEMP%\mkvimball.cmd"
	Erase "%TEMP%\mkvimball.cmd"
    )
    Exit /B %ERRORLEVEL%
)

Rem Invoke the output as a command
Rem Type "%TEMP%\mkvimball.cmd"
Call "%TEMP%\mkvimball.cmd"
Erase "%TEMP%\mkvimball.cmd" & Exit /B %ERRORLEVEL%
